baseURL: "amhelmi.github.io"
title: Ameer Helmi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2

params:
    description: "I am a person who does things."
    author: Ameer Helmi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ameer Helmi
          subtitle: "I am a person who does things."
          imageUrl: "IMG_7105.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/

    socialIcons:
        - name: CV
          url: AmeerHelmi_CV.pdf
        - name: Resume
          url: AmeerHelmi_Resume.pdf
        - name: Email
          url: mailto:ameer.helmi@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=xPGKU9oAAAAJ&hl=en&authuser=1
        - name: GitHub
          url: https://github.com/amhelmi
        - name: Linkedin
          url: https://www.linkedin.com/in/ameerhelmi/ 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: True
        hiddenInSingle: true
    label:
      text: "Ameer Helmi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2