baseURL: "amhelmi.github.io"
title: Ameer Helmi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Epic
          url: epic/
          weight: 2

params:
    author: Ameer Helmi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ameer Helmi, Ph.D.
          subtitle: "Roboticist and Healthcare Specialist with extensive experience in 
          **human-robot interaction**, **robot design**, **customer service**, and **Epic EMR build**. 
          My dissertation found evidence that modular assistive robots can promote physical activity for children with and without disabilities.

          I have my Ph.D. in Robotics from Oregon State University with 5+ years of robot and study design experience. 
          I have an additional 5+ years of experience working with Epic Beaker software and laboratory build. \n
                    
          Email: [ameer.helmi@gmail.com](mailto:ameer.helmi@gmail.com)"

          imageUrl: "/coverphoto.jpg"
          imageWidth: 320
          imageHeight: 320
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Epic
              url: epic/
            - name: Resume
              url: AmeerHelmi_Resume.pdf
            - name: Curriculum Vitae
              url: AmeerHelmi_CV.pdf


    socialIcons:
        - name: Email
          url: mailto:ameer.helmi@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=xPGKU9oAAAAJ&hl=en&authuser=1
        - name: GitHub
          url: https://github.com/amhelmi
        - name: Linkedin
          url: https://www.linkedin.com/in/ameerhelmi/ 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Ameer Helmi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2